name: Agni End-to-End Tests
on: [push, pull_request]
jobs:
  LLVM-to-SMT:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Linux sources
        run: |
          git clone -b v6.7 --depth 1 git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Generate encodings
        run: |
          cd ${{ github.workspace }}
          python3 generate_encodings.py --kernver 6.7 --kernbasedir ~/linux --outdir bpf-encodings/6.7 --specific-op BPF_SYNC
      - name:
        run: |
          pwd
          ls