name: LLVM-to-SMT Tests
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
jobs:
  llvm-to-smt:
    continue-on-error: true
    strategy:
      matrix:
        insn: [BPF_AND]
        kernel: [5.9, 6.8, latest]
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install -y \
            clang-12 llvm-12 llvm-12-tools llvm \
            python3 python3-pip \
            make cmake libelf-dev \
            libjsoncpp-dev stress-ng
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Show clang version(s)
        run: |
          whereis clang
          clang --version
          whereis clang-12
          clang-12 --version
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      - name: Retrieve Linux sources
        run: |
          branch=v${{ matrix.kernel }}
          if [ "${{ matrix.kernel }}" = "latest" ]; then
            branch=master
          fi
          git clone -qb $branch --depth 1 git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
      - name: Generate encodings
        run: |
          cd "${{ github.workspace }}/linux"
          commit=$(git rev-parse HEAD)
          cd -
          mkdir -p bpf-encodings/${{ matrix.kernel }}
          cd llvm-to-smt
          kernver=${{ matrix.kernel }}
          if [ "${{ matrix.kernel }}" = "latest" ]; then
            kernver="6.9-rc3"
          fi
          python3 generate_encodings.py \
            --kernver $kernver --commit $commit \
            --kernbasedir "${{ github.workspace }}/linux" \
            --outdir ../bpf-encodings/${{ matrix.kernel }} \
            --specific-op ${{ matrix.insn }} || echo "WE FAILED!!!!!!!"
          /home/runner/work/agni/agni/llvm-to-smt/llvm-passes/force_functions_early_exit.sh /home/runner/work/agni/agni/bpf-encodings/${{ matrix.kernel }}/BPF_AND/BPF_AND.Oz.ll /home/runner/work/agni/agni/bpf-encodings/${{ matrix.kernel }}/BPF_AND BPF_AND.Oz.ffee.ll
      - name: Check
        run: |
          ls bpf-encodings/${{ matrix.kernel }}
